spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/webide # TODO: 추후 MySQL로 변경
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
  jwt:
    secret: ${JWT_SECRET}
---
spring:
  output:
    ansi:
      enabled: ALWAYS
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # Hibernate(2.5) 버전 이후 추가된 옵션, Hibernate 초기화 이후 data.sql을 실행

  h2:
    console:
      enabled: true

---
spring:
  output:
    ansi:
      enabled: ALWAYS
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
